server:
  port: 10010
spring:
  cloud:
    gateway:
      routes:
      - id: car_route
        uri: lb://car-service
        predicates:
        - Path=/car-service/**
        filters:
        - StripPrefix=1
        order: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka